# Generated by Django 5.0.4 on 2024-05-26 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='times_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TagsDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_saved', models.BooleanField(default=True)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys_save.entrymodel')),
                ('TagsModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys_save.tagsmodel')),
            ],
            options={
                'db_table': 'tags_details',
            },
        ),
    ]
