# Generated by Django 5.0.4 on 2024-05-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
