# Generated by Django 5.0.4 on 2024-05-23 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0002_myuser_is_active_myuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsmodel',
            name='entrys_ids',
        ),
        migrations.AddField(
            model_name='tagsdetailmodel',
            name='entry_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrys_save.entrymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tagsdetailmodel',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagsDetails', to='entrys_save.tagsmodel'),
        ),
    ]
