# Generated by Django 5.0.4 on 2024-05-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0003_librarymodel_created_at_librarymodel_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsdetailmodel',
            old_name='TagsModel',
            new_name='tags_id',
        ),
        migrations.AlterField(
            model_name='tagsdetailmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
