# Generated by Django 5.0.4 on 2024-05-26 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0004_rename_tagsmodel_tagsdetailmodel_tags_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsdetailmodel',
            name='tags_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagsDetails', to='entrys_save.tagsmodel'),
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='users',
        ),
    ]
