# Generated by Django 5.0.4 on 2024-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0004_remove_tagsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
