# Generated by Django 5.0.4 on 2024-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0005_alter_tagsdetailmodel_tags_id_alter_myuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
