# Generated by Django 5.0.4 on 2024-05-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0005_tagsmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='entrys_saved',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
