# Generated by Django 5.0.4 on 2024-05-23 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0006_tagsmodel_entrys_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsmodel',
            name='entrys_saved',
        ),
    ]
