# Generated by Django 5.0.4 on 2024-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0006_librarymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='code_tag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
