# Generated by Django 5.0.4 on 2024-05-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys_save', '0007_tagsmodel_code_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsmodel',
            name='code_tag',
            field=models.CharField(max_length=10),
        ),
    ]
